---
- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Create directory
      file:
        name: /home/ansadmin/test
        state: directory
    - name: Create file
      file:
        name: /home/ansadmin/test/file1.txt
        state: touch
